### ISSUE TITLE
Errored Patcher

### ISSUE THREAD

**Issue by woodyafortunato** [tr4wzified/enblightpatcher#4]
Compiling
(C:\Users\woody\AppData\Local\Temp\Synthesis\dda88490-f597-4fcd-8829-e1d25fa24dab\Git\kngzxj3u.fv5\Runner\ENBLightPatcher): dotnet build --runtime win-x64 "ENBLightPatcher.csproj" -c Release
No extra data to consider.
Compiled
Sha 60d44adbfe4a3b24fcd94956d96bb639d8b5bef2
(): dotnet run --project "C:\Users\woody\AppData\Local\Temp\Synthesis\dda88490-f597-4fcd-8829-e1d25fa24dab\Git\kngzxj3u.fv5\Runner\ENBLightPatcher\ENBLightPatcher.csproj" -c Release --runtime win-x64 --no-build check-runnability --DataFolderPath "C:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data" --GameRelease SkyrimSE --LoadOrderFilePath C:\Users\woody\AppData\Local\Temp\Synthesis\dda88490-f597-4fcd-8829-e1d25fa24dab\Workspace\Plugins.txt
Running
(): dotnet run --project "C:\Users\woody\AppData\Local\Temp\Synthesis\dda88490-f597-4fcd-8829-e1d25fa24dab\Git\kngzxj3u.fv5\Runner\ENBLightPatcher\ENBLightPatcher.csproj" --runtime win-x64 --no-build -c Release run-patcher --DataFolderPath "C:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data" --ExtraDataFolder C:\Wabbajack\SMEFT\tools\Synthesis\Data\enblightpatcher --GameRelease SkyrimSE --LoadOrderFilePath C:\Users\woody\AppData\Local\Temp\Synthesis\dda88490-f597-4fcd-8829-e1d25fa24dab\Workspace\Plugins.txt --OutputPath "C:\Users\woody\AppData\Local\Temp\Synthesis\dda88490-f597-4fcd-8829-e1d25fa24dab\Workspace\10 - enblightpatcher" --PatcherName enblightpatcher --SourcePath "C:\Users\woody\AppData\Local\Temp\Synthesis\dda88490-f597-4fcd-8829-e1d25fa24dab\Workspace\9 - MortalEnemies-Patcher"
Mutagen version: 0.33.6
Mutagen sha: a8f8b368b106d950d0fb2362c0c64ee05c0e1fe6
Synthesis version: 0.20.5
Synthesis sha: 34cd545124be0cf01d98cd2f1d75f30d500c8a5b
run-patcher --DataFolderPath "C:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data" --ExtraDataFolder C:\Wabbajack\SMEFT\tools\Synthesis\Data\enblightpatcher --GameRelease SkyrimSE --LoadOrderFilePath C:\Users\woody\AppData\Local\Temp\Synthesis\dda88490-f597-4fcd-8829-e1d25fa24dab\Workspace\Plugins.txt --OutputPath "C:\Users\woody\AppData\Local\Temp\Synthesis\dda88490-f597-4fcd-8829-e1d25fa24dab\Workspace\10 - enblightpatcher" --PatcherName enblightpatcher --SourcePath "C:\Users\woody\AppData\Local\Temp\Synthesis\dda88490-f597-4fcd-8829-e1d25fa24dab\Workspace\9 - MortalEnemies-Patcher"
Prepping state.
RecordException Undriel_QRR Nav Fixed Patch.esp => : Arithmetic operation resulted in an overflow. System.OverflowException: Arithmetic operation resulted in an overflow.
   at Mutagen.Bethesda.Plugins.Binary.Overlay.PluginBinaryOverlay.FillMajorRecords(OverlayStream stream, Int32 finalPos, Int32 offset, Nullable`1 parseParams, RecordTypeFillWrapper fill)
   at Mutagen.Bethesda.Skyrim.Internals.WorldspaceSubBlockBinaryOverlay.WorldspaceSubBlockFactory(OverlayStream stream, BinaryOverlayFactoryPackage package, Nullable`1 parseParams)
   at Mutagen.Bethesda.Skyrim.Internals.WorldspaceBlockBinaryOverlay.<>c.<FillRecordType>b__39_0(ReadOnlyMemorySlice`1 s, BinaryOverlayFactoryPackage p, Nullable`1 recConv)
   at Mutagen.Bethesda.Plugins.Binary.Overlay.BinaryOverlayList.BinaryOverlayRecordListByLocationArray`1.GetEnumerator()+MoveNext()
   at Mutagen.Bethesda.Skyrim.ModContextExt.EnumerateMajorRecordContexts(IReadOnlyList`1 worldspaceBlocks, IWorldspaceGetter worldspace, ILinkCache linkCache, Type type, ModKey modKey, IModContext parent, Boolean throwIfUnknown, Func`3 getOrAddAsOverride)+MoveNext()
   at Mutagen.Bethesda.Skyrim.Internals.WorldspaceCommon.EnumerateMajorRecordContexts(IWorldspaceGetter obj, ILinkCache linkCache, Type type, ModKey modKey, IModContext parent, Boolean throwIfUnknown, Func`3 getOrAddAsOverride, Func`4 duplicateInto)+MoveNext()
   at Mutagen.Bethesda.Skyrim.Internals.SkyrimModCommon.EnumerateMajorRecordContexts(ISkyrimModGetter obj, ILinkCache linkCache, Type type, Boolean throwIfUnknown)+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Noggog.EnumerableExt.Catch[T](IEnumerable`1 e, Action`1 onException)+MoveNext() in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Extensions\EnumerableExt.cs:line 290   at Mutagen.Bethesda.Skyrim.SkyrimModMixIn.<>c__DisplayClass34_0`2.<EnumerateMajorRecordContexts>b__1(Exception e)
   at Noggog.EnumerableExt.Catch[T](IEnumerable`1 e, Action`1 onException)+MoveNext() in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Extensions\EnumerableExt.cs:line 292
   at Mutagen.Bethesda.OverrideMixIns.WinningOverrideContexts[TMod,TModGetter,TSetter,TGetter](IEnumerable`1 mods, ILinkCache linkCache, Boolean includeDeletedRecords)+MoveNext()
   at ENBLightPatcher.Program.RunPatch(IPatcherState`2 state) in C:\Users\woody\AppData\Local\Temp\Synthesis\dda88490-f597-4fcd-8829-e1d25fa24dab\Git\kngzxj3u.fv5\Runner\ENBLightPatcher\Program.cs:line 48
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 101
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, ModKey exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 507
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 428
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 400
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel)
   at Synthesis.Bethesda.Execution.Runner.Run[TKey](String workingDirectory, ModPath outputPath, String dataFolder, IEnumerable`1 loadOrder, GameRelease release, IEnumerable`1 patchers, IRunReporter`1 reporter, CancellationToken cancellation, ModPath sourcePath, PersistenceMode persistenceMode, String persistencePath)

Sorry I don't know what other info to provide than this.

**Comment by 1ceSpark** [comment]
I get the same error

**Comment by BrentW89** [comment]
I also get the same issue. This patcher seems to do nothing as far as I can tell. For me, I'm running Scenery ENB VR.

**Comment by Foul-Tarnished** [comment]
It worked before, F

**Comment by urbonx** [comment]
Yeah...having those issues now lol.
